title:              Sanghyun's Diary
email:              s_anghyun@naver.com
description:        Redeeming the time, because the days are evil (Ephesians 5:16)
author:             Sanghyun
baseurl:            ""
url:                "https://sh41om.github.io/"

# Social Profiles
twitter_username:   
github_username:    Sh41om
facebook_username:  
instagram_username: shalom_1412 
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
